import {cases,getCase,passage,version} from './corpus.mjs';
import {check} from './checker.mjs';
const lang=new URL(location.href).searchParams.get('lang')==='en'?'en':'fr';
const en={eyebrow:'One claim. All its conditions.',title:'The number is right.\nIs the meaning?',lede:'Compare a source passage with its restatement. Spot lost conditions, added promises and what automated checks cannot establish.',teaching:'Authored teaching examples',version:'Version 0.1 · FR / EN · No account',choose:'01 / Choose an information type',noScore:'No citability score',noScoreBody:'One missing condition may change a decision, even when several words have been reproduced correctly.',article:'Read the Edikka method',sourceLabel:'02 / Supplied information',sourceTitle:'The facts and their conditions',variant:'Presentation of the same content',distributed:'A · Distributed conditions',grouped:'B · Grouped conditions',sameFacts:'Both variants contain exactly the same sentences. Only their order changes. No effect on AI systems is assumed.',answerLabel:'03 / Examine the restatement',answerTitle:'What survives in the answer',example:'Example authored for this demonstration',careful:'Conditions retained',drift:'Meaning changed',short:'Too brief to conclude',custom:'Your own text',complete:'The text being examined is complete',local:'Your text is checked in this browser. The demo does not send it to a model or retain it.',check:'Examine the indicators',findingsLabel:'04 / Understand the checks',findingsTitle:'One finding for each condition',download:'Download the JSON findings',boundary:'“Indicator detected” means a rule found an expected expression. It does not certify overall fidelity. Complex negation or paraphrasing can remain indeterminate.',methodLabel:'What this can establish',methodTitle:'An open method.\nVisible boundaries.',readRules:'Read the rules and their limits',rulesBody:'These checks look for explicit indicators and a few predefined contradictions. They do not understand all paraphrases, negations or relationships between sentences. Failure to detect an indicator is not proof of an error. The examples expose both the successes and limits of the code.',checkerCode:'Read the checking code',corpus:'Read the FR/EN cases',realResults:'Check the status of AI experiments',noRuns:'No model experiment has been collected in this release. The supplied answers were authored to explain the checks; they are not observed model responses.',data:'Read the experiment data',protocol:'Reproduce the comparison',protocolBody:'Choose a question and freeze the variants and criteria before collection. Keep answers, errors, model identifiers, dates and conditions. Separate supplied text, a supplied URL and discovery without a URL. Null and unfavourable results belong in the experiment.',protocolFile:'Read the bilingual protocol',footer:'Prepare information. Preserve its meaning. Show the evidence.',documentation:'Documentation & reuse'};
document.documentElement.lang=lang;
if(lang==='en')for(const node of document.querySelectorAll('[data-i18n]')){const value=en[node.dataset.i18n];if(value){node.textContent='';value.split('\n').forEach((line,i)=>{if(i)node.append(document.createElement('br'));node.append(document.createTextNode(line));});}}
document.querySelector(`#lang-${lang}`).setAttribute('aria-current','page');
const $=s=>document.querySelector(s), text=(el,value)=>{el.textContent=value;};
$('#article-link').href=lang==='en'?'https://www.edikka.com/en/insights/seo/ai-citable-website':'https://www.edikka.com/insights/seo/site-citable-ia';
let current=getCase('price'),last=null;
const labels=lang==='fr'?{present:'Repère détecté',conflict:'Contradiction détectée',not_detected:'Non détecté',indeterminate:'Indéterminé'}:{present:'Indicator detected',conflict:'Conflict detected',not_detected:'Not detected',indeterminate:'Indeterminate'};
function source(){const content=passage(current,lang,$('#variant').value);$('#passage').replaceChildren(...content.split('\n\n').map(s=>{const p=document.createElement('p');text(p,s);return p;}));text($('#source-link'),current.sourceName+(lang==='fr'?' · Consulter la source':' · Read the source'));$('#source-link').href=current.source;text($('#source-date'),(current.sourceDate?(lang==='fr'?'Politique : ':'Policy: ')+current.sourceDate+' · ':'')+(lang==='fr'?'Source consultée : ':'Source reviewed: ')+current.reviewedAt);}
function examine(){last=check({caseId:current.id,text:$('#answer').value,lang,complete:$('#complete').checked});$('#controls').replaceChildren(...last.controls.map(r=>{const row=document.createElement('div');row.className='control';const body=document.createElement('div'),h=document.createElement('h4'),p=document.createElement('p'),tag=document.createElement('span');text(h,r.label);text(p,r.evidence.length?(lang==='fr'?'Formulation repérée : ':'Matched expression: ')+r.evidence.join(' · '):(lang==='fr'?'La règle ne permet pas de conclure sur cette condition.':'This rule cannot establish this condition.'));tag.className='status-label status-'+r.status;text(tag,labels[r.status]);body.append(h,p);row.append(body,tag);return row;}));text($('#status'),lang==='fr'?'Contrôles exécutés localement. Aucun jugement global de fidélité.':'Checks run locally. No overall fidelity verdict.');}
function chooseExample(){const id=$('#example').value;if(id!=='custom')$('#answer').value=current.examples[lang][id];$('#complete').checked=true;examine();}
function load(id){current=getCase(id);for(const b of $('#cases').children)b.setAttribute('aria-pressed',String(b.dataset.id===id));text($('#case-title'),current.title[lang]);text($('#question'),current.question[lang]);$('#example').value='careful';source();chooseExample();}
cases.forEach((c,i)=>{const b=document.createElement('button');b.type='button';b.dataset.id=c.id;const n=document.createElement('span');text(n,String(i+1).padStart(2,'0'));b.append(n,document.createTextNode(c.short[lang]));b.addEventListener('click',()=>load(c.id));$('#cases').append(b);});
$('#variant').addEventListener('change',source);$('#example').addEventListener('change',chooseExample);$('#answer').addEventListener('input',()=>{$('#example').value='custom';last=null;$('#controls').replaceChildren();text($('#status'),lang==='fr'?'Texte modifié : relancez les contrôles.':'Text changed: run the checks again.');});$('#complete').addEventListener('change',examine);$('#check').addEventListener('click',examine);
$('#download').addEventListener('click',()=>{examine();const payload={lab_version:version,exported_at:new Date().toISOString(),answer_origin:$('#example').value==='custom'?'user_supplied_unverified':'authored_teaching_example',source_url:current.source,variant:$('#variant').value,source_text:passage(current,lang,$('#variant').value),question:current.question[lang],answer:$('#answer').value,findings:last};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)+'\n'],{type:'application/json'}));a.download=`citation-fidelity-${current.id}-${lang}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
load('price');
