import {cases,getCase,passage,version} from './corpus.mjs';
import {check} from './checker.mjs';
const lang=new URL(location.href).searchParams.get('lang')==='en'?'en':'fr';
const en={eyebrow:'One claim. All its conditions.',title:'The number is right.\nIs the meaning?',lede:'Compare a source passage with its restatement. Spot lost conditions, added promises and what automated checks cannot establish.',teaching:'Teaching examples + collected answers',version:'Version 0.3 · FR / EN · No account',choose:'01 / Choose an information type',noScore:'No citability score',noScoreBody:'One missing condition may change a decision, even when several words have been reproduced correctly.',article:'Read the Edikka method',sourceLabel:'02 / Supplied information',sourceTitle:'The facts and their conditions',variant:'Presentation of the same content',distributed:'A · Distributed conditions',grouped:'B · Grouped conditions',sameFacts:'Both variants contain exactly the same sentences. Only their order changes. No effect on AI systems is assumed.',answerLabel:'03 / Examine the restatement',answerTitle:'What survives in the answer',example:'Text to examine',careful:'Conditions retained',drift:'Meaning changed',short:'Too brief to conclude',custom:'Your own text',complete:'The text being examined is complete',local:'Your text is checked in this browser. The demo does not send it to a model or retain it.',check:'Examine the indicators',findingsLabel:'04 / Understand the checks',findingsTitle:'One finding for each condition',download:'Download the JSON findings',boundary:'“Indicator detected” means a rule found an expected expression. It does not certify overall fidelity. Complex negation or paraphrasing can remain indeterminate.',methodLabel:'What this can establish',methodTitle:'An open method.\nVisible boundaries.',readRules:'Read the rules and their limits',rulesBody:'These checks look for explicit indicators and a few predefined contradictions. They do not understand all paraphrases, negations or relationships between sentences. Failure to detect an indicator is not proof of an error. The examples expose both the successes and limits of the code.',checkerCode:'Read the checking code',corpus:'Read the FR/EN cases',realResults:'Explore the collected answers',archive:'Open the original 36-run archive',noRuns:'Loading the collected experiment. Teaching examples remain clearly labelled and separate from real API answers.',data:'Read the 12 duration records',report:'Read the results and limitations',frozen:'Read the frozen experiment plan',protocol:'Reproduce the comparison',protocolBody:'Choose a question and freeze the variants and criteria before collection. Keep answers, errors, model identifiers, dates and conditions. Separate supplied text, a supplied URL and discovery without a URL. Null and unfavourable results belong in the experiment.',protocolFile:'Read the bilingual protocol',footer:'Prepare information. Preserve its meaning. Show the evidence.',documentation:'Documentation & reuse'};
document.documentElement.lang=lang;
if(lang==='en')for(const node of document.querySelectorAll('[data-i18n]')){const value=en[node.dataset.i18n];if(value){node.textContent='';value.split('\n').forEach((line,i)=>{if(i)node.append(document.createElement('br'));node.append(document.createTextNode(line));});}}
document.querySelector(`#lang-${lang}`).setAttribute('aria-current','page');
const $=s=>document.querySelector(s), text=(el,value)=>{el.textContent=value;};
$('#article-link').href=lang==='en'?'https://www.edikka.com/en/insights/seo/ai-citable-website':'https://www.edikka.com/insights/seo/site-citable-ia';
let current=getCase('price'),last=null,collected=[],selectedRun=null;
const labVersion='0.3.0';
const labels=lang==='fr'?{present:'Repère détecté',conflict:'Contradiction détectée',not_detected:'Non détecté',indeterminate:'Indéterminé'}:{present:'Indicator detected',conflict:'Conflict detected',not_detected:'Not detected',indeterminate:'Indeterminate'};
function source(){$('#case-limit').hidden=current.id!=='time';text($('#case-limit'),lang==='fr'?'Corpus 0.2 : « la refonte ciblée » remplace le renvoi ambigu. Douze nouveaux essais distincts ; les 36 premiers restent dans l’archive.':'Corpus 0.2: “a targeted redesign” replaces the ambiguous reference. Twelve separate follow-up calls; the original 36 remain archived.');const content=passage(current,lang,$('#variant').value);$('#passage').replaceChildren(...content.split('\n\n').map(s=>{const p=document.createElement('p');text(p,s);return p;}));text($('#source-link'),current.sourceName+(lang==='fr'?' · Consulter la source':' · Read the source'));$('#source-link').href=current.source;text($('#source-date'),(current.sourceDate?(lang==='fr'?'Politique : ':'Policy: ')+current.sourceDate+' · ':'')+(lang==='fr'?'Source consultée : ':'Source reviewed: ')+current.reviewedAt);}
function examine(){last=check({caseId:current.id,text:$('#answer').value,lang,complete:$('#complete').checked});$('#controls').replaceChildren(...last.controls.map(r=>{const row=document.createElement('div');row.className='control';const body=document.createElement('div'),h=document.createElement('h4'),p=document.createElement('p'),tag=document.createElement('span');text(h,r.label);text(p,r.evidence.length?(lang==='fr'?'Formulation repérée : ':'Matched expression: ')+r.evidence.join(' · '):(lang==='fr'?'La règle ne permet pas de conclure sur cette condition.':'This rule cannot establish this condition.'));tag.className='status-label status-'+r.status;text(tag,labels[r.status]);body.append(h,p);row.append(body,tag);return row;}));text($('#status'),lang==='fr'?'Contrôles exécutés localement. Aucun jugement global de fidélité.':'Checks run locally. No overall fidelity verdict.');}
function updateRunOptions(){
  $('#example optgroup[data-runs]')?.remove();
  const matches=collected.filter(r=>r.case_id===current.id&&r.language===lang&&r.variant===$('#variant').value&&r.answer);
  if(!matches.length)return;
  const group=document.createElement('optgroup');group.dataset.runs='true';group.label=lang==='fr'?'Réponses API collectées':'Collected API answers';
  for(const r of matches){const option=document.createElement('option');option.value='run:'+r.run_id;option.textContent=`GPT-6 Astra · ${lang==='fr'?'essai':'run'} ${r.repetition}${r.complete?'':(lang==='fr'?' (incomplet)':' (incomplete)')}`;group.append(option);}
  $('#example').append(group);
}
function chooseExample(){
  const id=$('#example').value;selectedRun=collected.find(r=>'run:'+r.run_id===id)??null;
  if(selectedRun){$('#answer').value=selectedRun.answer;$('#complete').checked=selectedRun.complete;text($('#answer-provenance'),`${lang==='fr'?'Réponse réelle':'Real response'} · ${selectedRun.returned_model} · ${new Date(selectedRun.ended_at).toLocaleDateString(lang==='fr'?'fr-FR':'en-GB')} · ${lang==='fr'?'texte fourni, sans recherche web':'supplied text, no web search'}`);}
  else{if(id!=='custom')$('#answer').value=current.examples[lang][id];$('#complete').checked=true;text($('#answer-provenance'),id==='custom'?(lang==='fr'?'Texte fourni par vous, provenance non vérifiée.':'Your own text; provenance unverified.'):(lang==='fr'?'Exemple rédigé pour la pédagogie. Ce texte ne vient pas d’un modèle.':'Authored teaching example. This text is not a model response.'));}
  examine();
}
function load(id){current=getCase(id);for(const b of $('#cases').children)b.setAttribute('aria-pressed',String(b.dataset.id===id));text($('#case-title'),current.title[lang]);text($('#question'),current.question[lang]);$('#example').value='careful';source();updateRunOptions();chooseExample();}
cases.forEach((c,i)=>{const b=document.createElement('button');b.type='button';b.dataset.id=c.id;const n=document.createElement('span');text(n,String(i+1).padStart(2,'0'));b.append(n,document.createTextNode(c.short[lang]));b.addEventListener('click',()=>load(c.id));$('#cases').append(b);});
$('#variant').addEventListener('change',()=>{source();const wasRun=Boolean(selectedRun);updateRunOptions();if(wasRun){$('#example').value='careful';chooseExample();}});$('#example').addEventListener('change',chooseExample);$('#answer').addEventListener('input',()=>{$('#example').value='custom';selectedRun=null;text($('#answer-provenance'),lang==='fr'?'Texte modifié par vous : ce n’est plus la réponse collectée intacte.':'Edited text: this is no longer an unchanged collected answer.');last=null;$('#controls').replaceChildren();text($('#status'),lang==='fr'?'Texte modifié : relancez les contrôles.':'Text changed: run the checks again.');});$('#complete').addEventListener('change',examine);$('#check').addEventListener('click',examine);
$('#download').addEventListener('click',()=>{examine();const payload={lab_version:labVersion,corpus_version:selectedRun?.corpus_version??version,exported_at:new Date().toISOString(),answer_origin:selectedRun?'collected_api_response':$('#example').value==='custom'?'user_supplied_unverified':'authored_teaching_example',collected_run:selectedRun?{run_id:selectedRun.run_id,model:selectedRun.returned_model,ended_at:selectedRun.ended_at,original_complete:selectedRun.complete,source:selectedRun.results_path,experiment_id:selectedRun.experiment_id,corpus_version:selectedRun.corpus_version}:null,source_url:current.source,variant:$('#variant').value,source_text:passage(current,lang,$('#variant').value),question:current.question[lang],answer:$('#answer').value,findings:last};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)+'\n'],{type:'application/json'}));a.download=`citation-fidelity-${current.id}-${lang}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
load('price');

async function loadCollected(){
  try{
    const response=await fetch('results.json');if(!response.ok)throw new Error('unavailable');
    const data=await response.json();
    const originalResponse=await fetch('archive/v0.2/results.json');if(!originalResponse.ok)throw new Error('archive unavailable');
    const original=await originalResponse.json();
    collected=[...data.runs.map(r=>({...r,corpus_version:'0.2.0',experiment_id:data.experiment_id,results_path:'results.json'})),...original.runs.filter(r=>r.case_id!=='time').map(r=>({...r,corpus_version:'0.1.0',experiment_id:original.experiment_id,results_path:'archive/v0.2/results.json'}))];
    if(collected.some(r=>r.source_text!==passage(getCase(r.case_id),r.language,r.variant)))throw new Error('source mismatch');
    const complete=collected.filter(r=>r.complete).length;
    const counts=data.counts??{attempted:collected.length,completed:complete,failed:0,incomplete:0};
    text($('#runs-note'),lang==='fr'?`Deux séries séparées : 36 essais initiaux conservés dans l’archive, puis ${counts.attempted} nouveaux essais de délai (${counts.completed} complets, ${counts.failed} échecs, ${counts.incomplete} incomplets). Le sélecteur utilise les 24 réponses prix/hébergement initiales et les 12 réponses du délai corrigé. GPT-6 Astra, trois essais par condition ; aucun effet général ni gain de citation démontré.`:`Two separate series: 36 original attempts preserved in the archive, then ${counts.attempted} new duration calls (${counts.completed} complete, ${counts.failed} failed, ${counts.incomplete} incomplete). The selector uses the original 24 price/hosting answers and the 12 corrected-duration answers. GPT-6 Astra, three runs per condition; no general effect or citation lift established.`);
    updateRunOptions();
  }catch{collected=[];$('#example optgroup[data-runs]')?.remove();text($('#runs-note'),lang==='fr'?'Les données d’essais ne sont pas disponibles. Les exemples pédagogiques restent utilisables.':'Experiment data is unavailable. Teaching examples remain usable.');}
}
loadCollected();
