import {inspectText} from './inspect.mjs';import {cases,passage} from '../corpus.mjs';
const lang=new URLSearchParams(location.search).get('lang')==='en'?'en':'fr',en=lang==='en',$=s=>document.querySelector(s),t=(fr,enText)=>en?enText:fr;
const tr={eyebrow:'YOUR TEXT / NO API',title:'Which conditions survive retrieval?',lead:'Paste a passage, ask a question and name the exact expressions to track. See which fragments are selected and which expressions stay outside.',privacy:'Everything runs in this tab. Your input is neither transmitted nor stored. No model answers your question.',results:'See the A/B/C experiment',archive:'Explore the previous series',inputTitle:'Put your passage through the splitter',textLabel:'Source passage',textHelp:'Up to 30,000 characters and 200 sentences. Splitting detects sentences and respects line breaks; inspect the displayed fragments to verify it.',questionLabel:'Reader’s question',watchLabel:'Conditions to track: exact expressions',watchHelp:'One expression copied from the passage per line, up to 20. This tool matches exact text, without interpreting its meaning.',size:'Sentences per fragment',topK:'Fragments selected',inspect:'Inspect fragments',example:'Load the price example',clear:'Clear my input',download:'Export my analysis',outputTitle:'What is selected and what stays outside',limitsTitle:'Visible splitting. Explicit limits.',limits:'Ranking reuses the lab’s frozen lexical rule: matching question terms divided by the square root of fragment term count. Default: three sentences, one fragment. Ties use source order. Automatic sentence segmentation is an added step for free text; a very long sentence remains indivisible.',limits2:'An expression outside the fragment may have an equivalent elsewhere; a present expression can still be misused. This does not predict Google retrieval, citations or AI answer fidelity. An expression absent from the source passage is not counted as lost.',code:'Your-text mode code',retriever:'Frozen retriever',footer:'Keep conditions visible, down to individual fragments.'};
document.documentElement.lang=lang;document.title=en?'Your text — Citation Fidelity Lab':'Votre texte — Citation Fidelity Lab';if(en)for(const e of document.querySelectorAll('[data-t]'))e.textContent=tr[e.dataset.t];$('#lang-'+lang).setAttribute('aria-current','page');for(const id of ['results-link','archive-link'])$('#'+id).href+='?lang='+lang;
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};let current=null;
function stale(){current=null;$('#download').disabled=true;$('#output').hidden=true;$('#status').textContent='';}
function example(){const c=cases.find(c=>c.id==='price');$('#text').value=passage(c,lang,'distributed');$('#question').value=c.question[lang];$('#watch').value=(en?['excluding VAT','up to three templates','Multilingual work and bespoke business integrations','neither a French market average nor an automatic quotation']:['€ HT','trois gabarits','Le multilingue et une intégration métier spécifique','ni une moyenne du marché français ni un devis automatique']).join('\n');stale();}
function render(){try{current=inspectText({text:$('#text').value,question:$('#question').value,watch:$('#watch').value.split('\n').map(x=>x.trim()).filter(Boolean),lang,size:Number($('#size').value),topK:Number($('#top-k').value)});$('#output').hidden=false;$('#download').disabled=false;const kept=current.checks.filter(x=>x.status==='retained').length,found=current.checks.filter(x=>x.status!=='not_in_source').length;$('#status').textContent=t(`${current.sentences} phrases ; ${kept}/${found} expressions présentes dans la source restent dans les fragments retenus.`,`${current.sentences} sentences; ${kept}/${found} expressions found in the source remain in selected fragments.`);
 $('#checks').replaceChildren(...current.checks.map(c=>{const d=el('div',undefined,'condition-status');d.append(el('strong',c.expression),el('span',c.status==='retained'?t('Présente dans un fragment retenu','Present in a selected fragment'):c.status==='not_in_source'?t('Introuvable dans la source — à corriger','Not found in source — check the expression'):t('En dehors des fragments retenus','Outside selected fragments')));return d;}));
 $('#chunks').replaceChildren(...current.ranked.map(c=>{const s=el('section',undefined,'panel'+(c.selected?' selected':''));s.append(el('h3',`${c.chunk_id} · ${c.selected?t('Retenu','Selected'):t('Non retenu','Not selected')}`),el('p',t('Score lexical : ','Lexical score: ')+c.score.toFixed(3),'chunk-score'));for(const f of c.facts)s.append(el('p',f.fact_id+' · '+f.text));return s;}));
 }catch{stale();$('#status').textContent=t('Ajoutez un passage et une question. Limites : 30 000 caractères, 200 phrases, 20 expressions de 300 caractères maximum.','Add a passage and a question. Limits: 30,000 characters, 200 sentences, 20 expressions of up to 300 characters.');}}
$('#inspect').addEventListener('click',render);$('#example').addEventListener('click',example);for(const id of ['text','question','watch','size','top-k'])$('#'+id).addEventListener('input',stale);$('#clear').addEventListener('click',()=>{for(const id of ['text','question','watch'])$('#'+id).value='';stale();$('#text').focus();});$('#download').addEventListener('click',()=>{if(!current)return;const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(current,null,2)+'\n'],{type:'application/json'}));a.href=url;a.download='citation-fragments-'+lang+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});example();
