import {cases,conditions,supplied} from '../attached/corpus.mjs';import {inspect} from '../attached/measure.mjs';
const lang=new URLSearchParams(location.search).get('lang')==='en'?'en':'fr',en=lang==='en',$=s=>document.querySelector(s),t=(f,e)=>en?e:f;
document.documentElement.lang=lang;document.title=t('Claude et OpenAI — Citation Fidelity Lab','Claude and OpenAI — Citation Fidelity Lab');if(en)for(const e of document.querySelectorAll('[data-en]'))e.textContent=e.dataset.en;$('#lang-'+lang).setAttribute('aria-current','page');$('#workbench').href='../workbench/?lang='+lang;
const el=(tag,text)=>{const n=document.createElement(tag);n.textContent=text;return n;};for(const c of cases){const o=el('option',c.short[lang]);o.value=c.id;$('#case').append(o);}let data=null;
function showProvider(k,r){$('#'+k+'-declarations').replaceChildren();$('#'+k+'-answer').textContent=r?.answer||t('Pas de réponse complète disponible pour cet essai.','No complete response available for this run.');$('#'+k+'-raw').textContent=r?.raw_output??'';$('#'+k+'-meta').textContent=r?`${r.run_id} · ${r.complete?t('réponse complète','complete response'):t('échec ou sortie incomplète','failed or incomplete')} · ${r.estimated_cost_usd??'?'} USD`:t('Non tenté','Not attempted');
 for(const m of r?inspect(r.parsed_output,r.sentences).conditions:[]){const category=conditions[r.case_id].find(x=>x[0]===m.condition_id);const d=el('p',m.condition_id+' · '+category[en?2:1]+' · '+(m.provided?t('fournie','supplied'):t('absente','absent'))+' · '+t('déclaration : ','declaration: ')+m.declared);if(m.declared==='available')d.append(el('br',''),document.createTextNode(t('preuve selon le codage : ','evidence under coding: ')+(m.exact_supplied_evidence?t('validée','valid'):t('non validée','not valid'))));$('#'+k+'-declarations').append(d);}
}
function render(){if(!data)return;const c=cases.find(c=>c.id===$('#case').value),v=$('#variant').value,m=$('#mode').value,rep=+$('#repetition').value,s=supplied(c,lang,v,m);$('#question').textContent=c.question[lang];$('#provided').textContent=s.provided_condition_ids.length+'/4 '+t('conditions fournies avant génération, pour les deux modèles.','conditions supplied before generation, to both models.');$('#source').replaceChildren(...s.sentences.map(x=>el('p','['+x.sentence_id+'] '+x.text)));for(const k of ['openai','anthropic'])showProvider(k,data[k].runs.find(r=>r.case_id===c.id&&r.language===lang&&r.variant===v&&r.mode===m&&r.repetition===rep));}
for(const e of document.querySelectorAll('select'))e.addEventListener('change',render);
try{const [oa,an,s]=await Promise.all(['../attached/results.json','results.json','summary.json'].map(async u=>{const r=await fetch(u);if(!r.ok)throw Error();return r.json();}));data={openai:oa,anthropic:an};$('#status').textContent=t(`${s.all_valid_counts.openai} réponses GPT-6 Astra ; ${s.all_valid_counts.anthropic} réponses Claude ; ${s.paired_count} paires complètes comparables.`,`${s.all_valid_counts.openai} GPT-6 Astra responses; ${s.all_valid_counts.anthropic} Claude responses; ${s.paired_count} complete matched pairs.`);render();}catch{$('#status').textContent=t('Données indisponibles. Consultez le rapport lié ci-dessus.','Data unavailable. Read the linked report above.');}
