import {readFile,writeFile,open,mkdir,rename} from 'node:fs/promises';import {createHash} from 'node:crypto';import {resolve,dirname} from 'node:path';import {fileURLToPath} from 'node:url';import {parseEnv} from 'node:util';
import {model,endpoint,budgetUsd,reserveUsd,canStart,observation,redact,makePlan} from './collect.mjs';
const root=dirname(fileURLToPath(import.meta.url)),sha=b=>createHash('sha256').update(b).digest('hex');
const get=async f=>JSON.parse(await readFile(resolve(root,f)));
async function state(){const plan=await get('experiment.json'),first=await get('transport-interruption/results.json'),ledger=await get('transport-interruption/ledger.json');if(JSON.stringify(plan.runs)!==JSON.stringify(makePlan())||first.status!=='stopped'||first.runs.length!==78||first.counts.complete!==77)throw Error('Unexpected predecessor');for(const [f,h]of Object.entries(plan.hashes))if(sha(await readFile(resolve(root,f)))!==h)throw Error('Frozen input changed');const attempted=new Set(first.runs.map(r=>r.run_id)),remaining=plan.runs.filter(r=>!attempted.has(r.run_id));if(remaining.length!==30||attempted.size!==78||ledger.length!==78)throw Error('Run membership changed');return {plan,first,ledger,remaining};}
async function hashes(){const out={};for(const f of ['experiment.json','transport-interruption/results.json','transport-interruption/ledger.json','CONTINUATION.md','continue.mjs'])out[f]=sha(await readFile(resolve(root,f)));return out;}
async function save(f,d){await writeFile(f+'.tmp',JSON.stringify(d,null,2)+'\n',{mode:0o600});await rename(f+'.tmp',f);}
export async function freeze(){const s=await state(),p={schema_version:1,frozen_at:new Date().toISOString(),experiment_id:s.plan.experiment_id+'-continuation',budget_usd:budgetUsd,prior_known_usd:s.first.estimated_cost_usd,prior_unsettled_usd:s.first.unsettled_reserved_usd,runs:s.remaining,hashes:await hashes()};const f=await open(resolve(root,'continuation.json'),'wx');await f.writeFile(JSON.stringify(p,null,2)+'\n');await f.close();return {remaining:p.runs.length,prior_known_usd:p.prior_known_usd,prior_unsettled_usd:p.prior_unsettled_usd};}
export async function collect(outDir,keyFile){const s=await state(),p=await get('continuation.json');if(JSON.stringify(p.hashes)!==JSON.stringify(await hashes())||JSON.stringify(p.runs)!==JSON.stringify(s.remaining))throw Error('Continuation changed');const key=parseEnv(await readFile(keyFile,'utf8')).ANTHROPIC_API_KEY;if(!key)throw Error('Missing access');await mkdir(outDir,{recursive:true,mode:0o700});const f=await open(resolve(outDir,'.collection-lock'),'wx',0o600);await f.close();const ledger=[],r={schema_version:1,experiment_id:p.experiment_id,provider:'Anthropic',model,status:'collecting',started_at:new Date().toISOString(),planned_count:30,estimated_cost_usd:0,unsettled_reserved_usd:0,runs:[],stopped_reason:null};
 for(const run of p.runs){const reserve=reserveUsd(run.request);if(!canStart([...s.ledger,...ledger],reserve)){r.stopped_reason='budget';break;}const entry={run_id:run.run_id,started_at:new Date().toISOString(),reserved_usd:reserve,settled_cost_usd:null};ledger.push(entry);await save(resolve(outDir,'ledger.json'),ledger);let body=null,status=null,id=null,err=null;
  try{const res=await fetch(endpoint,{method:'POST',headers:{'x-api-key':key,'anthropic-version':'2023-06-01','Content-Type':'application/json'},body:JSON.stringify(run.request),redirect:'error',signal:AbortSignal.timeout(120000)});status=res.status;id=res.headers.get('request-id');body=JSON.parse(redact(await res.text(),key));}catch{err='transport_or_json_error_unknown_billing';}
  const row={...run,request:undefined,started_at:entry.started_at,ended_at:new Date().toISOString(),request_id:id,...observation(run,body,status,key),transport_error:err};r.runs.push(row);entry.settled_cost_usd=row.estimated_cost_usd;r.estimated_cost_usd=Number(ledger.reduce((a,b)=>a+(b.settled_cost_usd??0),0).toFixed(8));r.unsettled_reserved_usd=Number(ledger.filter(x=>x.settled_cost_usd===null).reduce((a,b)=>a+b.reserved_usd,0).toFixed(8));await save(resolve(outDir,'results.json'),r);await save(resolve(outDir,'ledger.json'),ledger);console.log(JSON.stringify({continuation_done:r.runs.length,planned:30,complete:row.complete,known_total_usd:Number((s.first.estimated_cost_usd+r.estimated_cost_usd).toFixed(8))}));
  if(err||status!==200||row.estimated_cost_usd===null||!row.complete||!row.valid_shape||row.returned_model!==model||row.estimated_cost_usd>reserve){r.stopped_reason=err??'technical_or_budget_failure';break;}
 }
 r.status=r.stopped_reason?'stopped':'complete';r.ended_at=new Date().toISOString();r.counts={attempted:r.runs.length,complete:r.runs.filter(x=>x.complete&&x.valid_shape).length,failed:r.runs.filter(x=>x.http_status!==200).length,incomplete:r.runs.filter(x=>x.http_status===200&&(!x.complete||!x.valid_shape)).length,unattempted:30-r.runs.length};await save(resolve(outDir,'results.json'),r);return {status:r.status,...r.counts,cost:r.estimated_cost_usd};
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){const a=process.argv.slice(2);try{console.log(JSON.stringify(a[0]==='--freeze'?await freeze():await collect(resolve(a[0]),resolve(a[1]))));}catch(e){console.error(redact(e.message));process.exitCode=1;}}
