import {cases,conditions,supplied} from './corpus.mjs';import {inspect} from './measure.mjs';
const lang=new URLSearchParams(location.search).get('lang')==='en'?'en':'fr',en=lang==='en',$=s=>document.querySelector(s),t=(fr,eng)=>en?eng:fr;
const texts={measurementNote:'Diagnostic limitation: overlapping categories, coding distinct from meaning',eyebrow:'Experiment 04 · Attached conditions',title:'When a condition is missing,\ndoes the model say so?',lede:'Three layouts, the same retriever. Variant C attaches conditions to key sentences. Compare what reaches the model with what it declares unavailable.',limit:'C also changes length and repetition. Missing-information diagnostics are explicitly requested. This experiment does not measure spontaneous behaviour or web citation.',report:'Results and limitations',protocol:'Frozen protocol',records:'Every response',explore:'Explore one response',case:'Case',variant:'Layout',distributed:'A · Distributed conditions',grouped:'B · Grouped conditions',attached:'C · Conditions within the sentence',mode:'Supplied text',retrieved:'One fragment · 3 sentences',full:'Control · 6 sentences',repetition:'Independent repetition',sourceLabel:'01 / Before generation',sourceTitle:'Sentences actually supplied',withheld:'Show withheld sentences',answerLabel:'02 / After generation',answerTitle:'Unmodified collected answer',quotes:'Model declarations and extracts',raw:'Show raw output',download:'Download this run as JSON',conditions:'Supplied conditions, declared gaps',conditionsNote:'Availability comes from the plan; declarations come from the model. Exact evidence checks a supplied sentence and substring, not semantic fidelity.',sensitivity:'Change retrieval settings',sensitivityNote:'72 retrieval-only combinations. No model call happens here; see which sentences the retriever selects for the current case and language.',size:'Sentences per fragment',topK:'Fragments selected',ranking:'Lexical score: matching distinct question terms / square root of fragment term count. Ties use source order. No web search or embeddings.',methodTitle:'One experiment.\nExplicit limits.',methodBody:'108 planned runs: three cases, two languages, three layouts, two input modes, three repetitions. The initial transport failure is retained without retry. The pilot with biased labels is archived separately. One provider; Claude has not been evaluated.',plan:'Frozen plan and hashes',summary:'Calculated summary',code:'Frozen retrieval code',legacy:'Review the previous retrieval experiment',footer:'Make supplied information and declared gaps visible.',documentation:'Documentation and reuse'};
document.documentElement.lang=lang;document.title=t('Conditions attachées — Citation Fidelity Lab','Attached conditions — Citation Fidelity Lab');
if(en)for(const el of document.querySelectorAll('[data-i18n]'))if(texts[el.dataset.i18n])el.replaceChildren(...texts[el.dataset.i18n].split('\n').flatMap((s,i)=>i?[document.createElement('br'),document.createTextNode(s)]:[document.createTextNode(s)]));
$('#lang-'+lang).setAttribute('aria-current','page');$('#legacy-link').href='../retrieval/?lang='+lang;$('#workbench-link').href='../workbench/?lang='+lang;
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const sentence=f=>{const n=el('p');n.append(el('span',f.sentence_id??f.fact_id,'fact-id'),document.createTextNode(f.text));return n;};
for(const c of cases){const n=el('option',c.short[lang]);n.value=c.id;$('#case').append(n);}let data=null,selected=null;
function sensitivity(c){$('#sensitivity').replaceChildren(...['distributed','grouped','attached'].map(v=>{const r=supplied(c,lang,v,'retrieved',{size:+$('#size').value,topK:+$('#top-k').value}),n=el('section',undefined,'panel');n.append(el('h3',$('#variant option[value="'+v+'"]').textContent),el('p',r.provided_condition_ids.length+'/4 '+t('conditions fournies','conditions supplied')));for(const ch of r.retrieval.ranked){const box=el('div',undefined,'chunk'),active=r.retrieval.selected_chunk_ids.includes(ch.chunk_id);box.append(el('p',ch.chunk_id+' · '+ch.score.toFixed(3)+' · '+(active?t('retenu','selected'):t('non retenu','not selected')),active?'chunk-selected':''),...ch.facts.map(sentence));n.append(box);}return n;}));}
function render(){const c=cases.find(c=>c.id===$('#case').value),variant=$('#variant').value,mode=$('#mode').value,s=supplied(c,lang,variant,mode);selected=data?.runs.find(r=>r.case_id===c.id&&r.language===lang&&r.variant===variant&&r.mode===mode&&r.repetition===+$('#repetition').value)??null;$('#question').textContent=c.question[lang];sensitivity(c);$('#source-facts').replaceChildren(...s.sentences.map(sentence));const missing=supplied(c,lang,variant,'full').sentences.filter(f=>!s.sentences.some(p=>p.sentence_id===f.sentence_id));$('#withheld-facts').replaceChildren(...(missing.length?missing.map(sentence):[el('p',t('Les six phrases sont fournies.','All six sentences are supplied.'))]));$('#retrieval-note').textContent=s.provided_condition_ids.length+'/4 '+t('conditions réellement fournies.','conditions actually supplied.');
 $('#answer').textContent=selected?.answer||t('Réponse indisponible : échec ou essai non tenté.','Response unavailable: failed or unattempted run.');$('#raw').textContent=selected?.raw_output??'';$('#answer-meta').textContent=selected?`${selected.returned_model??'—'} · ${selected.ended_at} · ${selected.complete?t('complète','complete'):t('échec ou incomplète','failed or incomplete')} · $${selected.estimated_cost_usd??'?'} ${t('HT estimés','estimated before tax')}`:'';
 const checks=selected?.complete?inspect(selected.parsed_output,selected.sentences).conditions:[];
 $('#quotes').replaceChildren(...checks.map(q=>{const n=el('div');n.append(el('p',q.condition_id+' · '+(q.declared==='available'?t('déclarée disponible','declared available'):t('déclarée indisponible','declared unavailable')),'small'));if(q.quote)n.append(el('blockquote',q.quote),el('p',q.exact_supplied_evidence?t('Extrait exact valide','Valid exact extract'):t('Preuve exacte non validée','Exact evidence not validated'),'small'));return n;}));
 $('#conditions').replaceChildren(...conditions[c.id].map(([id,fr,eng])=>{const q=checks.find(q=>q.condition_id===id),n=el('div',undefined,'condition-row'),provided=s.provided_condition_ids.includes(id);n.append(el('strong',id+' · '+(en?eng:fr)),el('span',provided?t('Fournie','Supplied'):t('Absente','Absent')),el('span',q?(q.declared==='available'?t('Déclarée disponible','Declared available'):t('Déclarée absente','Declared missing')):t('Pas de déclaration','No declaration')));return n;}));$('#download').disabled=!selected;
}
for(const id of ['case','variant','mode','repetition','size','top-k'])$('#'+id).addEventListener('change',render);
$('#download').addEventListener('click',()=>{if(!selected)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(selected,null,2)],{type:'application/json'}));a.download=selected.run_id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});render();
try{const response=await fetch('results.json');if(!response.ok)throw Error();data=await response.json();if(data.status!=='final')throw Error();$('#collection-status').textContent=t(`${data.counts.complete}/108 réponses complètes ; ${data.counts.failed} échecs, ${data.counts.incomplete} incomplets, ${data.counts.unattempted} non tentés. Série : ${data.estimated_cost_usd} $ HT connus. Cumul connu : ${data.known_cumulative_cost_usd} $ ; réserves incertaines : ${data.unsettled_reserved_usd} $.`,`${data.counts.complete}/108 complete responses; ${data.counts.failed} failed, ${data.counts.incomplete} incomplete, ${data.counts.unattempted} unattempted. Known series estimate: USD ${data.estimated_cost_usd}. Known cumulative estimate: USD ${data.known_cumulative_cost_usd}; unresolved reservations: USD ${data.unsettled_reserved_usd}.`);render();}catch{data=null;$('#collection-status').textContent=t('Collecte indisponible ; la récupération reste explorable.','Collection unavailable; retrieval remains explorable.');render();}
