import {readFile,writeFile,open,mkdir,rename} from 'node:fs/promises';
import {createHash} from 'node:crypto';import {resolve,dirname} from 'node:path';import {fileURLToPath} from 'node:url';import {parseEnv} from 'node:util';
import {cases,supplied,conditions} from './corpus.mjs';import {inspect} from './measure.mjs';import {rates,usageCost,redact} from '../collect.mjs';
const root=dirname(fileURLToPath(import.meta.url)),sha=b=>createHash('sha256').update(b).digest('hex');
export const priorSpentUsd=3.550768,budgetUsd=9.50,endpoint='https://api.openai.com/v1/responses';
const item={type:'object',additionalProperties:false,properties:{availability:{type:'string',enum:['available','not_available']},sentence_id:{type:'string',enum:['','S1','S2','S3','S4','S5','S6']},quote:{type:'string'}},required:['availability','sentence_id','quote']};
const schema={type:'object',additionalProperties:false,properties:{answer:{type:'string'},conditions_not_available:{type:'array',items:{type:'string',enum:['F1','F2','F3','F4']}},conditions:{type:'object',additionalProperties:false,properties:Object.fromEntries(['F1','F2','F3','F4'].map(id=>[id,item])),required:['F1','F2','F3','F4']}},required:['answer','conditions_not_available','conditions']};
export function reserveUsd(request){return Math.ceil(((Buffer.byteLength(JSON.stringify(request))+1024)*rates.cache_write+request.max_output_tokens*rates.output))/1e6;}
export function canStart(spent,reserved){return Number.isFinite(spent)&&Number.isFinite(reserved)&&spent>=0&&reserved>=0&&spent+reserved<=budgetUsd;}
export function makePlan(){const runs=[];for(const c of cases)for(let rep=1;rep<=3;rep++)for(const [li,language] of ['fr','en'].entries()){
 const base=['distributed','grouped','attached'],shift=(rep+li)%3,variants=[...base.slice(shift),...base.slice(0,shift)];
 for(const [vi,variant] of variants.entries())for(const mode of (rep+vi)%2?['retrieved','full']:['full','retrieved']){
  const s=supplied(c,language,variant,mode);const instruction=language==='fr'?'Réponds en français en 80 mots maximum, uniquement avec les phrases fournies. Conserve les limites, nomme la source, signale une information manquante sans la deviner. Pour chaque catégorie F1–F4, déclare available seulement si les phrases fournies renseignent cette catégorie ; cite alors un identifiant S et un extrait exact de 16 caractères minimum. Sinon déclare not_available et laisse sentence_id et quote vides. Liste toutes les catégories not_available dans conditions_not_available. Les catégories sont des questions de contrôle, pas des faits à supposer.':'Answer in English in at most 80 words using only supplied sentences. Preserve limits, name the source, and flag missing information without guessing. For each category F1–F4, declare available only if the supplied sentences inform it; then cite an S identifier and an exact extract of at least 16 characters. Otherwise declare not_available and leave sentence_id and quote empty. List every not_available category in conditions_not_available. Categories are checks, not facts to assume.';
  const input=instruction+'\n\nQuestion: '+c.question[language]+'\nSource: '+c.sourceName+'\n\nCategories:\n'+conditions[c.id].map(([id,fr,en])=>id+': '+(language==='fr'?fr:en)).join('\n')+'\n\n'+s.sentences.map(x=>'['+x.sentence_id+'] '+x.text).join('\n\n');
  const request={model:'gpt-6-astra',input,reasoning:{effort:'medium'},max_output_tokens:1600,service_tier:'default',store:false,tools:[],text:{format:{type:'json_schema',name:'availability_diagnostic',strict:true,schema}}};
  runs.push({run_id:`attached-v2-${c.id}-${language}-${variant}-${mode}-r${rep}`,case_id:c.id,language,variant,mode,repetition:rep,question:c.question[language],source_url:c.source,...s,request});
 }}return runs;}
async function hashes(){const out={};for(const f of ['corpus.mjs','measure.mjs','collect.mjs','PROTOCOL.md','../corpus.mjs','../corpus.json','../retrieval/retrieve.mjs','../retrieval/results.json','../results.json','../archive/v0.2/results.json','../collect.mjs','../attached-pilot/results.json','../attached-pilot/ledger.json','../attached-pilot/ERRATUM.md'])out[f]=sha(await readFile(resolve(root,f)));return out;}
async function validatePlan(experimentPath){
 const originalPath=resolve(root,'experiment.json'),originalBytes=await readFile(originalPath),original=JSON.parse(originalBytes),priorBytes=await readFile(resolve(root,'transport-interruption/results.json')),previous=JSON.parse(priorBytes),plan=JSON.parse(await readFile(experimentPath));
 // Validate the frozen original implementation without making a request.
 const {collect:dry}=await import('./collect.mjs');await dry({experimentPath:originalPath,outDir:'/unused',execute:false});
 const failedIds=previous.runs.map(r=>r.run_id),remaining=original.runs.filter(r=>!failedIds.includes(r.run_id));
 if(plan.original_sha256!==sha(originalBytes)||plan.interruption_sha256!==sha(priorBytes)||plan.collector_sha256!==sha(await readFile(fileURLToPath(import.meta.url)))||JSON.stringify(plan.runs)!==JSON.stringify(remaining)||plan.prior_spent_usd!==priorSpentUsd)throw new Error('Continuation freeze changed');
 return {plan,previous};
}
export async function freeze(target){
 const bytes=await readFile(resolve(root,'experiment.json')),original=JSON.parse(bytes),previousBytes=await readFile(resolve(root,'transport-interruption/results.json')),previous=JSON.parse(previousBytes),ids=previous.runs.map(r=>r.run_id),runs=original.runs.filter(r=>!ids.includes(r.run_id));
 const plan={schema_version:1,experiment_id:original.experiment_id+'-continuation',frozen_at:new Date().toISOString(),original_sha256:sha(bytes),interruption_sha256:sha(previousBytes),collector_sha256:sha(await readFile(fileURLToPath(import.meta.url))),prior_spent_usd:priorSpentUsd,prior_known_cost_usd:3.29503,unsettled_reserved_usd:0.255738,reason:'Continue 107 unattempted runs; do not replay the failed first run. Identical requests and order. Transport cause unknown. Previous failed run is retained in aggregate.',planned_count:runs.length,runs};
 const f=await open(target,'wx');await f.writeFile(JSON.stringify(plan,null,2)+'\n');await f.close();return plan;
}
async function save(p,x){await writeFile(p+'.tmp',JSON.stringify(x,null,2)+'\n',{mode:0o600});await rename(p+'.tmp',p);}
export async function collect({experimentPath,outDir,keyFile,execute=false,fetchImpl=fetch}){
 const bytes=await readFile(experimentPath),{plan}=await validatePlan(experimentPath);if(!execute)return {planned:plan.runs.length,network_calls:0,per_call_reserved_max:Math.max(...plan.runs.map(r=>reserveUsd(r.request)))};
 const key=keyFile?(parseEnv(await readFile(keyFile,'utf8')).OPENAI_API_KEY??''):(process.env.OPENAI_API_KEY??'');if(!key.trim())throw new Error('Missing API access');await mkdir(outDir,{recursive:true,mode:0o700});const lock=await open(resolve(outDir,'.collection-lock'),'wx',0o600);await lock.writeFile(sha(bytes));await lock.close();
 const result={schema_version:1,experiment_id:plan.experiment_id,experiment_sha256:sha(bytes),status:'collecting',started_at:new Date().toISOString(),planned_count:plan.runs.length,prior_spent_usd:priorSpentUsd,estimated_cost_usd:0,cumulative_estimated_cost_usd:priorSpentUsd,runs:[],stopped_reason:null};const ledger=[];
 for(const run of plan.runs){const reserve=reserveUsd(run.request);if(!canStart(result.cumulative_estimated_cost_usd,reserve)){result.stopped_reason='budget';break;}const entry={run_id:run.run_id,reserved_usd:reserve,started_at:new Date().toISOString(),settled_cost_usd:null};ledger.push(entry);await save(resolve(outDir,'ledger.json'),ledger);
  let body=null,status=null,failed=false,transportDetail=null;try{const response=await fetchImpl(endpoint,{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify(run.request),signal:AbortSignal.timeout(120000)});status=response.status;body=await response.json();}catch(e){failed=true;transportDetail={name:e?.name??null,code:e?.cause?.code??null};}
  const messages=body?.output?.filter(x=>x.type==='message')??[],raw=messages.flatMap(x=>x.content??[]).filter(x=>x.type==='output_text').map(x=>x.text).join('\n');let parsed=null;try{parsed=JSON.parse(raw);}catch{}
  const complete=status===200&&body?.status==='completed'&&messages.length>0&&messages.every(m=>m.status==='completed')&&Boolean(raw.trim());const measured=inspect(parsed,run.sentences),cost=usageCost(body?.usage);
  const row={...run,request:undefined,started_at:entry.started_at,ended_at:new Date().toISOString(),http_status:status,returned_model:body?.model??null,response_id:body?.id??null,response_status:body?.status??null,complete,raw_output:redact(raw,key),parsed_output:parsed,answer:parsed?.answer??'',measurements:measured,usage:body?.usage??null,estimated_cost_usd:cost,error_type:body?.error?.type??(failed?'transport_error':null),transport_detail:transportDetail};
  result.runs.push(row);entry.settled_cost_usd=cost;result.estimated_cost_usd=Number(result.runs.reduce((s,r)=>s+(r.estimated_cost_usd??0),0).toFixed(8));result.cumulative_estimated_cost_usd=Number((priorSpentUsd+result.estimated_cost_usd).toFixed(8));await save(resolve(outDir,'results.json'),result);await save(resolve(outDir,'ledger.json'),ledger);
  console.log(JSON.stringify({done:result.runs.length,planned:plan.runs.length,complete,cumulative_usd:result.cumulative_estimated_cost_usd}));
  if(cost===null||!complete||!measured.valid_shape||cost>reserve){result.stopped_reason=cost===null?'unknown_usage':!complete?'incomplete_or_failed':!measured.valid_shape?'invalid_shape':'reservation_exceeded';break;}
 }
 result.status=result.stopped_reason?'stopped':'complete';result.ended_at=new Date().toISOString();result.counts={attempted:result.runs.length,complete:result.runs.filter(r=>r.complete).length,incomplete:result.runs.filter(r=>r.http_status===200&&!r.complete).length,failed:result.runs.filter(r=>r.http_status!==200).length,unattempted:plan.runs.length-result.runs.length};await save(resolve(outDir,'results.json'),result);return {status:result.status,...result.counts,cumulative_estimated_cost_usd:result.cumulative_estimated_cost_usd};
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){const a=process.argv.slice(2),v=k=>a.includes(k)?a[a.indexOf(k)+1]:undefined;try{if(v('--freeze')){const p=await freeze(resolve(v('--freeze')));console.log(JSON.stringify({frozen:true,planned:p.planned_count,worst_case:p.full_plan_worst_case_usd,progressive_cap:budgetUsd}));}else console.log(JSON.stringify(await collect({experimentPath:resolve(v('--experiment')),outDir:resolve(v('--out')),keyFile:v('--key-file'),execute:a.includes('--execute')})));}catch(e){console.error(redact(e.message,process.env.OPENAI_API_KEY??''));process.exitCode=1;}}
