import {cases} from '../corpus.mjs';
import {conditions,retrieve} from './retrieve.mjs';
const lang=new URLSearchParams(location.search).get('lang')==='en'?'en':'fr',en=lang==='en';
const translations={attachedLink:'Explore the new C variant',workbenchLink:'Try your text, without an API',eyebrow:'Experiment 03 · Fragment retrieval',title:'What the model receives.\nWhat it can cite.',lede:'The same sentences in a different order. Compare conditions available in the selected fragments, then the extracts cited in the collected answers.',limit:'Local lexical simulation on three authored cases. It does not reproduce Google or measure web citation frequency. A verbatim extract does not certify the meaning of the whole answer.',report:'Read the results and limitations',protocol:'Read the frozen protocol',records:'Read every response',explore:'Explore one response',case:'Case',variant:'Sentence order',distributed:'A · Distributed conditions',grouped:'B · Grouped conditions',mode:'Supplied text',retrieved:'One fragment · 3 sentences',full:'Control · 6 sentences',repetition:'Independent repetition',sourceLabel:'01 / Before generation',sourceTitle:'Sentences actually supplied',withheld:'Show withheld sentences',answerLabel:'02 / After generation',answerTitle:'Unmodified collected answer',quotes:'Extracts declared by the model',raw:'Show raw output',download:'Download this run as JSON',conditions:'Four conditions, two separate observations',conditionsNote:'“Supplied” checks whether the source sentence was present in the input. “Exact extract cited” checks the declared evidence; it does not guarantee that the answer respects this condition.',sensitivity:'Change retrieval settings',sensitivityNote:'All 48 retrieval combinations are published. No model calls happen here: this simulation only shows selected sentences for the chosen case and language.',size:'Sentences per fragment',topK:'Fragments selected',ranking:'Lexical score: distinct matching question terms / square root of fragment term count. Ties use source order. No web search or embeddings.',methodTitle:'One experiment.\nExplicit limits.',methodBody:'The 72 planned calls cross three cases, two languages, two variants, two modes and three repetitions. The earlier 48 responses remain a separate experiment. Settings were frozen before calls. This series evaluates one provider; no cross-provider robustness is established.',plan:'Full plan and file hashes',summary:'Calculated summary',code:'Retrieval code',legacy:'Return to teaching examples and earlier series',footer:'Make supplied information and the limits of reuse visible.',documentation:'Documentation and reuse'};
const $=s=>document.querySelector(s),t=(fr,english)=>en?english:fr;
document.documentElement.lang=lang;
if(en)for(const el of document.querySelectorAll('[data-i18n]')){const value=translations[el.dataset.i18n];if(value)el.replaceChildren(...value.split('\n').flatMap((line,i)=>i?[document.createElement('br'),document.createTextNode(line)]:[document.createTextNode(line)]));}
$('#lang-'+lang).setAttribute('aria-current','page');$('#legacy-link').href='../?lang='+lang;
function element(tag,text,className){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;}
for(const c of cases){const opt=element('option',c.short[lang]);opt.value=c.id;$('#case').append(opt);}
let data=null,selected=null;
const factNode=f=>{const p=element('p');p.append(element('span',f.fact_id,'fact-id'),document.createTextNode(f.text));return p;};
function sensitivity(c){$('#sensitivity').replaceChildren(...['distributed','grouped'].map(variant=>{const r=retrieve(c,lang,variant,{size:Number($('#size').value),topK:Number($('#top-k').value)}),section=element('section',undefined,'panel'),title=element('h3',variant==='distributed'?t('A · Dispersées','A · Distributed'):t('B · Rapprochées','B · Grouped'));section.append(title,element('p',`${r.facts.filter(f=>conditions[c.id].some(([id])=>id===f.fact_id)).length}/4 ${t('phrases portant les conditions disponibles','condition-bearing sentences available')}`));for(const ch of r.ranked){const block=element('div',undefined,'chunk'),active=r.selected_chunk_ids.includes(ch.chunk_id);block.append(element('p',`${ch.chunk_id} · ${t('score','score')} ${ch.score.toFixed(3)} · ${active?t('retenu','selected'):t('non retenu','not selected')}`,active?'chunk-selected':''),...ch.facts.map(factNode));section.append(block);}return section;}));}
function render(){const c=cases.find(c=>c.id===$('#case').value),variant=$('#variant').value,mode=$('#mode').value;$('#question').textContent=c.question[lang];sensitivity(c);selected=data?.runs.find(r=>r.case_id===c.id&&r.language===lang&&r.variant===variant&&r.mode===mode&&r.repetition===Number($('#repetition').value))??null;
 const r=retrieve(c,lang,variant),facts=selected?.source_facts??(mode==='retrieved'?r.facts:c.order[variant].map(i=>({fact_id:`F${i+1}`,text:c.facts[lang][i]})));
 $('#source-facts').replaceChildren(...facts.map(factNode));const missing=c.order[variant].map(i=>({fact_id:`F${i+1}`,text:c.facts[lang][i]})).filter(f=>!facts.some(p=>p.fact_id===f.fact_id));$('#withheld-facts').replaceChildren(...(missing.length?missing.map(factNode):[element('p',t('Aucune : les six phrases ont été fournies.','None: all six sentences were supplied.'))]));
 $('#retrieval-note').textContent=mode==='retrieved'?t(`Fragment ${r.selected_chunk_ids.join(', ')} retenu sur ${r.ranked.length}.`,`Fragment ${r.selected_chunk_ids.join(', ')} selected out of ${r.ranked.length}.`):t('Témoin complet : mêmes consignes, mêmes paramètres, six phrases.','Full-text control: same instructions and parameters, six sentences.');
 $('#answer').textContent=selected?.answer||t('Aucune réponse disponible pour cet essai.','No response available for this run.');$('#raw').textContent=selected?.raw_output??'';
 $('#answer-meta').textContent=selected?`${selected.returned_model??'—'} · ${selected.ended_at} · ${selected.complete?t('complète','complete'):t('incomplète ou en échec','incomplete or failed')} · $${selected.estimated_cost_usd??'?'} ${t('HT calculés','estimated before tax')}`:'';
 $('#quotes').replaceChildren(...(selected?.evidence_checks.quotes??[]).map(q=>{const div=element('div');div.append(element('p',`${q.fact_id} · ${q.exact_substring?t('extrait exact fourni','exact supplied extract'):t('extrait non validé','extract not validated')}`,'small'),element('blockquote',q.quote));return div;}));
 $('#conditions').replaceChildren(...conditions[c.id].map(([id,fr,english])=>{const row=element('div',undefined,'condition-row'),provided=facts.some(f=>f.fact_id===id),cited=selected?.evidence_checks.valid_cited_fact_ids.includes(id);row.append(element('strong',`${id} · ${en?english:fr}`),element('span',provided?t('Phrase fournie','Sentence supplied'):t('Phrase absente','Sentence absent')),element('span',selected?(cited?t('Extrait exact cité','Exact extract cited'):t('Aucun extrait exact cité','No exact extract cited')):t('Réponse indisponible','Response unavailable')));return row;}));$('#download').disabled=!selected;
}
for(const id of ['case','variant','mode','repetition','size','top-k'])$('#'+id).addEventListener('change',render);
$('#download').addEventListener('click',()=>{if(!selected)return;const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([JSON.stringify({experiment_id:data.experiment_id,experiment_sha256:data.experiment_sha256,run:selected},null,2)+'\n'],{type:'application/json'}));link.download=selected.run_id+'.json';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);});
render();
try{const response=await fetch('results.json');if(!response.ok)throw new Error('unavailable');data=await response.json();if(data.status==='collecting')throw new Error('not final');$('#collection-status').textContent=t(`${data.counts.attempted}/${data.planned_count} essais · ${data.counts.complete} complets · ${data.counts.failed} échecs · ${data.counts.incomplete} incomplets. Coût calculé de cette série : ${data.estimated_cost_usd} $ HT ; cumul avec les 48 précédents : ${data.cumulative_estimated_cost_usd} $ HT.`,`${data.counts.attempted}/${data.planned_count} runs · ${data.counts.complete} complete · ${data.counts.failed} failed · ${data.counts.incomplete} incomplete. Estimated series cost: USD ${data.estimated_cost_usd} before tax; cumulative with the earlier 48: USD ${data.cumulative_estimated_cost_usd}.`);render();}catch{data=null;$('#collection-status').textContent=t('Données indisponibles : la récupération reste explorable, aucune réponse n’est inventée.','Records unavailable: retrieval remains explorable; no answer is invented.');render();}

$('#attached-link').href='../attached/?lang='+lang;$('#workbench-link').href='../workbench/?lang='+lang;
